plugins {
    id 'org.jetbrains.kotlin.jvm' version '2.2.21' apply false
    id 'org.openjfx.javafxplugin' version '0.1.0' apply false
}

allprojects {
    group = 'com.allan.atools'
    version = '1.6.0'
}

subprojects {
    plugins.withType(JavaPlugin).configureEach {
        java {
            toolchain {
                languageVersion = JavaLanguageVersion.of(17)
            }
            modularity.inferModulePath = false
        }

        tasks.withType(JavaCompile).configureEach {
            options.encoding = 'UTF-8'
            options.release = 17
        }

        tasks.named('compileJava', JavaCompile) {
            doFirst {
                options.compilerArgs.addAll(['--module-path', classpath.asPath])
                classpath = files()
            }
        }
    }
}

apply from: 'gradle/packaging-config.gradle'
apply from: 'gradle/packaging-helpers.gradle'
apply from: 'gradle/packaging-tasks.gradle'
