/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_allan_jni_TextManager */

#ifndef _Included_com_allan_jni_TextManager
#define _Included_com_allan_jni_TextManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_allan_jni_TextManager
 * Method:    say
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_allan_jni_TextManager_say
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_allan_jni_TextManager
 * Method:    generate
 * Signature: (Ljava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_allan_jni_TextManager_generate
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
