<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.allan.atools</groupId>
        <artifactId>ATools</artifactId>
        <version>1.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>Notepadmm</artifactId>
    <packaging>jar</packaging>

    <dependencies>
        <dependency>
            <groupId>com.allan.atools</groupId>
            <artifactId>BaseParty</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.allan.atools</groupId>
            <artifactId>BaseUiLibs</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>

    <build>
        <directory>${project.parent.basedir}/target</directory>
        <sourceDirectory>${project.basedir}/main/java</sourceDirectory>
        <testSourceDirectory>${project.basedir}/test/java</testSourceDirectory>
        <resources>
            <resource>
                <directory>${project.basedir}/main/resources</directory>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>
